name = "jsl-omega-network"
main = "worker/worker.js"
compatibility_date = "2026-08-04"

[[d1_databases]]
binding = "DB"
database_name = "jsl_omega_network"
database_id = "7b92b057-19aa-4959-87d2-0aa324ee0250"

# npx wrangler secret put OMEGA_NETWORK_KEY
